// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CheckForUpdates():Promise<domain.Result_map_string_interface____>;

export function DeleteConnection(arg1:string):Promise<domain.Result_bool_>;

export function DownloadUpdate():Promise<domain.Result_bool_>;

export function GetConnections():Promise<domain.Result___map_string_interface____>;

export function GetPlatform():Promise<domain.Result_string_>;

export function GetSettings():Promise<domain.Result_map_string_interface____>;

export function GetUpdateStatus():Promise<domain.Result_map_string_interface____>;

export function GetVersion():Promise<domain.Result_string_>;

export function InstallUpdate():Promise<domain.Result_bool_>;

export function LaunchCitrix(arg1:Record<string, any>,arg2:Record<string, any>):Promise<domain.Result_bool_>;

export function LaunchHorizon(arg1:Record<string, any>,arg2:Record<string, any>):Promise<domain.Result_bool_>;

export function LaunchRdp(arg1:Record<string, any>,arg2:Record<string, any>):Promise<domain.Result_bool_>;

export function LaunchVpn():Promise<domain.Result_bool_>;

export function Log(arg1:string,arg2:string):Promise<domain.Result_bool_>;

export function NetworkGeo():Promise<domain.Result_map_string_interface____>;

export function NetworkPing(arg1:string,arg2:number):Promise<domain.Result_map_string_interface____>;

export function ResetDefaultConnections():Promise<domain.Result___map_string_interface____>;

export function SaveConnection(arg1:Record<string, any>):Promise<domain.Result_bool_>;

export function SaveSettings(arg1:Record<string, any>):Promise<domain.Result_bool_>;
