// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload() {
  return window['go']['app']['App']['CancelDownload']();
}

export function CheckForUpdates() {
  return window['go']['app']['App']['CheckForUpdates']();
}

export function DeleteConnection(arg1) {
  return window['go']['app']['App']['DeleteConnection'](arg1);
}

export function DownloadUpdate() {
  return window['go']['app']['App']['DownloadUpdate']();
}

export function GetConnections() {
  return window['go']['app']['App']['GetConnections']();
}

export function GetPlatform() {
  return window['go']['app']['App']['GetPlatform']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetUpdateStatus() {
  return window['go']['app']['App']['GetUpdateStatus']();
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function InstallNow() {
  return window['go']['app']['App']['InstallNow']();
}

export function InstallOnQuit() {
  return window['go']['app']['App']['InstallOnQuit']();
}

export function LaunchCitrix(arg1, arg2) {
  return window['go']['app']['App']['LaunchCitrix'](arg1, arg2);
}

export function LaunchHorizon(arg1, arg2) {
  return window['go']['app']['App']['LaunchHorizon'](arg1, arg2);
}

export function LaunchRdp(arg1, arg2) {
  return window['go']['app']['App']['LaunchRdp'](arg1, arg2);
}

export function LaunchVpn() {
  return window['go']['app']['App']['LaunchVpn']();
}

export function Log(arg1, arg2) {
  return window['go']['app']['App']['Log'](arg1, arg2);
}

export function NetworkGeo() {
  return window['go']['app']['App']['NetworkGeo']();
}

export function NetworkPing(arg1, arg2) {
  return window['go']['app']['App']['NetworkPing'](arg1, arg2);
}

export function ResetDefaultConnections() {
  return window['go']['app']['App']['ResetDefaultConnections']();
}

export function SaveConnection(arg1) {
  return window['go']['app']['App']['SaveConnection'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function TrackConnectionLaunch(arg1) {
  return window['go']['app']['App']['TrackConnectionLaunch'](arg1);
}

export function TrackError(arg1) {
  return window['go']['app']['App']['TrackError'](arg1);
}

export function TrackEvent(arg1, arg2) {
  return window['go']['app']['App']['TrackEvent'](arg1, arg2);
}

export function TrackHelpView(arg1) {
  return window['go']['app']['App']['TrackHelpView'](arg1);
}

export function TrackNetworkCheck() {
  return window['go']['app']['App']['TrackNetworkCheck']();
}

export function TrackTabView(arg1) {
  return window['go']['app']['App']['TrackTabView'](arg1);
}
